# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
install:
 - sudo apt-get install libimage-exiftool-perl
 - git clone git://github.com/smarnach/pyexiftool.git
 - ln -s ../pyexiftool/exiftool.py src/exiftool.py
 - pip install pylint==1.3.1
 - pip install pyflakes
 - pip install pep8
script:
  - pep8 src
  - pylint --rcfile=pylintrc src
  - pyflakes src
  - nosetests src
